//----------------------------------------------------------------------------
// Author           : Álvaro Ibáñez del Pino
// NickName         : aibanez
// Created          : 28-08-2021
//
// Last Modified By : aibanez
// Last Modified On : 18-11-2023
// Description      : v1.7.1
//
// Copyright        : (C)  2023 by Sothis/Nunsys. All rights reserved.       
//----------------------------------------------------------------------------
using System;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using VisionNet.Core.Encoding;

namespace VisionNet.Core.Security
{
    /// <summary>
    /// Provides encryption and decryption helpers for secure strings using either Base64 encoding or TripleDES encryption.
    /// </summary>
    public class PasswordEncriptDecript
    {
        private SecureString _securityKey = new SecureString();


        /// <summary>
        /// Initializes a new instance of the <see cref="PasswordEncriptDecript"/> class with the built-in security key required for TripleDES operations.
        /// </summary>
        public PasswordEncriptDecript()
        {
            _securityKey.AppendChar('S');
            _securityKey.AppendChar('o');
            _securityKey.AppendChar('t');
            _securityKey.AppendChar('h');
            _securityKey.AppendChar('i');
            _securityKey.AppendChar('s');
            _securityKey.AppendChar('1');
            _securityKey.AppendChar('9');
            _securityKey.AppendChar('.');
        }

        /// <summary>
        /// Encrypts the provided secure text by either performing Base64 encoding or applying TripleDES encryption in ECB mode with PKCS7 padding.
        /// </summary>
        /// <param name="source">Secure string containing the plaintext to encrypt; the instance must be non-null and not disposed.</param>
        /// <param name="encriptMethod">Encryption strategy to apply. Use <see cref="EncriptMethod.Base64"/> for reversible Base64 encoding or <see cref="EncriptMethod.ECB"/> for TripleDES encryption.</param>
        /// <returns>A Base64-encoded string representing the encrypted data.</returns>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="source"/> is <see langword="null"/>.</exception>
        /// <exception cref="ObjectDisposedException">Thrown when <paramref name="source"/> has already been disposed.</exception>
        /// <exception cref="CryptographicException">Thrown when the cryptographic provider cannot create an encryptor or encryption fails.</exception>
        public string Encript(SecureString source, EncriptMethod encriptMethod = EncriptMethod.Base64)
        {
            switch (encriptMethod)
            {
                case EncriptMethod.Base64:
                default:
                    return new Base64EncoderDecoder().Encode(source.FromSecureString());

                case EncriptMethod.ECB:

                    // Getting the bytes of Input String.
                    byte[] toEncryptedArray = UTF8Encoding.UTF8.GetBytes(source.FromSecureString());

                    MD5CryptoServiceProvider objMD5CryptoService = new MD5CryptoServiceProvider();
                    //Gettting the bytes from the Security Key and Passing it to compute the Corresponding Hash Value.
                    byte[] securityKeyArray = objMD5CryptoService.ComputeHash(UTF8Encoding.UTF8.GetBytes(_securityKey.FromSecureString()));
                    //De-allocatinng the memory after doing the Job.
                    objMD5CryptoService.Clear();

                    var objTripleDESCryptoService = new TripleDESCryptoServiceProvider();
                    //Assigning the Security key to the TripleDES Service Provider.
                    objTripleDESCryptoService.Key = securityKeyArray;
                    //Mode of the Crypto service is Electronic Code Book.
                    objTripleDESCryptoService.Mode = CipherMode.ECB;
                    //Padding Mode is PKCS7 if there is any extra byte is added.
                    objTripleDESCryptoService.Padding = PaddingMode.PKCS7;

                    var objCrytpoTransform = objTripleDESCryptoService.CreateEncryptor();
                    //Transform the bytes array to resultArray
                    byte[] resultArray = objCrytpoTransform.TransformFinalBlock(toEncryptedArray, 0, toEncryptedArray.Length);
                    objTripleDESCryptoService.Clear();
                    return Convert.ToBase64String(resultArray, 0, resultArray.Length);
            }
        }

        /// <summary>
        /// Decrypts the provided text by reversing either the Base64 encoding or the TripleDES encryption performed by <see cref="Encript"/>.
        /// </summary>
        /// <param name="source">Base64-encoded cipher text to decrypt; must contain data generated by the corresponding <see cref="Encript"/> overload.</param>
        /// <param name="encriptMethod">Decryption strategy to use. Select <see cref="EncriptMethod.Base64"/> for Base64 decoding or <see cref="EncriptMethod.ECB"/> for TripleDES decryption.</param>
        /// <returns>A <see cref="SecureString"/> holding the decrypted plaintext.</returns>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="source"/> is <see langword="null"/>.</exception>
        /// <exception cref="FormatException">Thrown when <paramref name="source"/> is not a valid Base64 string.</exception>
        /// <exception cref="CryptographicException">Thrown when the cryptographic provider cannot create a decryptor or the cipher text is invalid for the configured key.</exception>
        /// <exception cref="DecoderFallbackException">Thrown when decrypted bytes cannot be converted into UTF-8 text.</exception>
        public SecureString Decript(string source, EncriptMethod encriptMethod = EncriptMethod.Base64)
        {
            switch (encriptMethod)
            {
                case EncriptMethod.Base64:
                default:
                    return new Base64EncoderDecoder().Decode(source).ToSecureString();

                case EncriptMethod.ECB:

                    byte[] toEncryptArray = Convert.FromBase64String(source);
                    MD5CryptoServiceProvider objMD5CryptoService = new MD5CryptoServiceProvider();

                    //Gettting the bytes from the Security Key and Passing it to compute the Corresponding Hash Value.
                    byte[] securityKeyArray = objMD5CryptoService.ComputeHash(UTF8Encoding.UTF8.GetBytes(_securityKey.FromSecureString()));
                    objMD5CryptoService.Clear();

                    var objTripleDESCryptoService = new TripleDESCryptoServiceProvider();
                    //Assigning the Security key to the TripleDES Service Provider.
                    objTripleDESCryptoService.Key = securityKeyArray;
                    //Mode of the Crypto service is Electronic Code Book.
                    objTripleDESCryptoService.Mode = CipherMode.ECB;
                    //Padding Mode is PKCS7 if there is any extra byte is added.
                    objTripleDESCryptoService.Padding = PaddingMode.PKCS7;

                    var objCrytpoTransform = objTripleDESCryptoService.CreateDecryptor();
                    //Transform the bytes array to resultArray
                    byte[] resultArray = objCrytpoTransform.TransformFinalBlock(toEncryptArray, 0, toEncryptArray.Length);
                    objTripleDESCryptoService.Clear();

                    //Convert and return the decrypted data/byte into string format.
                    return UTF8Encoding.UTF8.GetString(resultArray).ToSecureString();
            }
        }
    }
}